# Generated by Django 4.2.7 on 2023-12-04 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BaseProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('type', models.IntegerField()),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('brand_name', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('item_unit', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('main_category', models.IntegerField()),
                ('stock_maintain', models.BooleanField(default=False)),
                ('alert_qnty', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariety',
            fields=[
                ('abstractbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.abstractbase')),
                ('variation_name', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('variation_value', models.FloatField(blank=True, null=True)),
                ('variety', models.IntegerField(blank=True, null=True)),
            ],
            bases=('product.abstractbase',),
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='product.category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_hsn', models.IntegerField(blank=True, null=True)),
                ('item_code', models.IntegerField(blank=True, null=True)),
                ('mrp', models.IntegerField(blank=True, null=True)),
                ('buy_rate', models.FloatField(blank=True, null=True)),
                ('sale_rate', models.FloatField(blank=True, null=True)),
                ('dis_percentage', models.FloatField(blank=True, null=True)),
                ('gst_percentage', models.FloatField(blank=True, null=True)),
                ('available_qty', models.IntegerField(blank=True, null=True)),
                ('product_expiry', models.DateField()),
                ('variant_stock_maintain', models.BooleanField(default=False)),
                ('base_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.baseproduct')),
            ],
        ),
        migrations.AddField(
            model_name='baseproduct',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_product', to='product.subcategory'),
        ),
        migrations.CreateModel(
            name='VarirtyImages',
            fields=[
                ('abstractbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.abstractbase')),
                ('image', models.ImageField(upload_to='./media/')),
                ('variety', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='varieties', to='product.productvariety')),
            ],
            bases=('product.abstractbase',),
        ),
        migrations.AddField(
            model_name='productvariety',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='varieties', to='product.product'),
        ),
    ]
