# Generated by Django 4.2.7 on 2023-12-04 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseproduct',
            name='main_category',
        ),
        migrations.RemoveField(
            model_name='baseproduct',
            name='type',
        ),
    ]
