# Generated by Django 4.2.7 on 2023-12-04 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_baseproduct_main_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='varirtyimages',
            name='image',
            field=models.ImageField(upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='varirtyimages',
            name='variety',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.productvariety'),
        ),
    ]
